### ISSUE TITLE
Plan id is not updating after billing

### ISSUE THREAD

**Issue by yasir-naseer-tetralogicx** [osiset/laravel-shopify#968] opened 2021-09-07 20:34 UTC
I have setup a fresh app and using billing feature, the app works fine and also perform the billing successfully, but after payment, the plan_id is not updating in the user table

Also i tried to manually edit it using $user->plan_id = 1; $user->save() which returns me true, still it is not updating

**Comment by Kyon147** [comment] 2021-11-03 11:05
Duplicate of #1002

**Closed** 2021-11-03 11:05 UTC
Labels: needs-info
