### ISSUE TITLE
Osiset\ShopifyApp\Exceptions\MissingShopDomainException

### ISSUE THREAD

**Issue by m4mehdi** [osiset/laravel-shopify#696] opened 2021-02-19 12:28 UTC
After Creating a new laravel project and  installing osiset/laravel-shopify tjhe welcome page is not show.
The error is MissingShopDomainException.

        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5",
        "osiset/laravel-shopify": "^16.0"

<img width="884" alt="1" src="https://user-images.githubusercontent.com/18750432/108504555-52528780-72cb-11eb-8d95-fe5f48b34a17.png">

**Comment by PhiloNL** [comment] 2021-02-20 14:43
This is because you are not authenticated. 

1. Login at https://partners.shopify.com/
2. Create a new application
3. Update your Laravel .env to include your app credentials
4. In the Shopify Partners portal click install your application into a demo store:

![Screenshot 2021-02-20 at 15 43 01](https://user-images.githubusercontent.com/1133950/108599585-52698a80-7392-11eb-91b7-7eba12fc0c74.png)

Once the app is installed you should see the welcome page.

**Comment by osiset** [comment] 2021-02-22 13:32
@m4mehdi Please use issue template and fill in all details so we can reproduce.

**Comment by maganius** [comment] 2021-02-24 16:03
@osiset I have same problem, the welcome page work correctly the first time I install the app because hmac and the others variable are setted in query string but when I try go to another page laravel throw the exception `Osiset\ShopifyApp\Exceptions\MissingShopDomainException`.

I have vue SPA but it throw the same error with this `<a href="{{ route('home') }}">HOME</a>`

**Comment by osiset** [comment] 2021-02-26 19:06
Closing, lack of issue template.

**Closed by osiset** 2021-02-26 19:06 UTC
