### ISSUE TITLE
Laravel 9 

### ISSUE THREAD

**Issue by jalpab** [osiset/laravel-shopify#1159] opened 2022-06-24 06:30 UTC
Laravel 9 version does not support to osiset/laravel-shopify package for shopify so any suggestions for this? and please can you give any approx time when an updated version of this package is launching?

**Comment by zeeshanhaider6236dev** [comment] 2022-06-27 05:32
Laravel 9 its still in pending, i hope this will be review and osiset new release available with laravel 9

**Comment by jalpab** [comment] 2022-06-28 06:20
@zeeshanhaider6236dev any other option to use shopify in laravel 9

**Comment by KingFisch** [comment] 2022-07-16 15:47
is there still no update from devs?

**Comment by zeeshanhaider6236dev** [comment] 2022-07-18 11:00
Yes

**Comment by fjarrett** [comment] 2022-08-18 21:35
Duplicate of #1157

**Closed** 2022-08-26 08:52 UTC
