### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by deepakroy11** [osiset/laravel-shopify#536] opened 2020-07-24 09:48 UTC
*For bug reporting only! If you're posting a feature request or discussion, please ignore.*

## Expected Behavior

Should authentication the application.

## Current Behavior

After app installation on Shopify, it redirects back to my app URL and then getting an authentication error.

## Failure Information
Getting below error,

GuzzleHttp\Exception\ClientException
Client error: POST https://deroy-theme-app.myshopify.com/admin/oauth/access_token resulted in a 400 Bad Request response:
https://simple-wishlist.test/authenticate?code=d422372968fe1ff0369ceca20cbb5194&hmac=0369aefe2eb0a0e3b8ff00276dfd91f7cfc8875656cf5f75973d44deea4933ee&shop=deroy-theme-app.myshopify.com&timestamp=1595496677

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install Laravel and include Shopify-Laravel package
2. Create a Shopify app and configure the API key, scope in the local setup.
3. Install the app in Shopify using the admin panel or app URL

Note: I am running Ubuntu 20.04 on my laptop and using Valet-Linux to set up the  application on my local host. 

### Context

* Package Version: v12.10
* Laravel Version: v7.0
* PHP Version: v7.4.1
* Using a toolset (Docker, Laradock, Vagrant, etc.): Valet-Linux

### Failure Logs

GuzzleHttp\Exception\ClientException
Client error: POST https://deroy-theme-app.myshopify.com/admin/oauth/access_token resulted in a 400 Bad Request response:
https://simple-wishlist.test/authenticate?code=d422372968fe1ff0369ceca20cbb5194&hmac=0369aefe2eb0a0e3b8ff00276dfd91f7cfc8875656cf5f75973d44deea4933ee&shop=deroy-theme-app.myshopify.com&timestamp=1595496677.

**Comment by osiset** [comment] 2020-07-24 17:09
Not having this issue.

Have you configured your API key and API secret? What are you asking in terms of scopes?

**Comment by deepakroy11** [comment] 2020-07-25 05:46
Yes, All keys are configured. In face to install the app, I was directed to Shopify where all the permission were listed. After clicking install I was redirected to above URL.

Permission I am requesting for. read_products,write_products,read_themes,write_themes,read_orders,read_customers.

**Comment by darrynten** [comment] 2020-07-27 08:50
This has started happening on new installs for me.

Using latest master of both this package and the basic API package and the issue is present when creating a new install.

It seems there is no body sent in the POST request to `/admin/oauth/access_token`

**Comment by osiset** [comment] 2020-07-27 12:43
Are you sure theres no post data sent? Ran through Xdebug and I am seeing params go through, but I will give a fresh install a try. This could be an issue with Guzzle if nothing is being sent but is being passed.

**Comment by darrynten** [comment] 2020-10-15 06:09
Might be resolved in #601

**Comment by osiset** [comment] 2020-11-01 23:20
@deepakroy11 Is this still an issue?

**Comment by osiset** [comment] 2021-01-21 18:09
Closing for need of info, reopen if you need.

**Closed by osiset** 2021-01-21 18:09 UTC

**Comment by simoni2cool** [comment] 2022-09-13 06:16
Hello , I have facing issue in shopify authentication,,
My shopify app are unpublished because of issue in authentication,
The app login still working after uninstall app,
it only work in one refresh.. I mean when i uninstall app from shopify and refresh app web page only one time it page still shows login ,, after other refresh it work proper
