### ISSUE TITLE
Osiset\ShopifyApp\Exceptions\MissingAuthUrlException (Missing auth url)

### ISSUE THREAD

**Issue by yasir-naseer-tetralogicx** [osiset/laravel-shopify#908] opened 2021-07-17 13:20 UTC
I recently updated form version 16 to 17, but on installing the app on a store i causing this bug, not sure what i missed, any help would be appreciated 
![Capture](https://user-images.githubusercontent.com/69499815/126038311-547edab5-51fe-4e29-b308-169c5887bee6.PNG)

**Comment by osiset** [comment] 2021-07-19 13:13
Sounds like you may be hitting line 96 on InstallShop.php... not sure how to reproduce this atm though.
Can you try using `dev-master` in Composer, there was a recent PR to these files that may help.

**Comment by ratapof** [comment] 2021-07-21 02:40
Hello, same issue!
 Im trying to setup a new project with laravel 8 and your package. i followed the [the instalation instructions](https://github.com/osiset/laravel-shopify/wiki/Installation) and i am getting exactly the same error.
 Osiset\ShopifyApp\Exceptions\MissingAuthUrlException
Missing auth url
at vendor\osiset\laravel-shopify\src\Traits\AuthController.php:47

**Comment by SkullDark1** [comment] 2021-07-22 03:43
Hello, I got the same issue. Does anyone get the solution?

**Comment by ratapof** [comment] 2021-07-28 02:48
i got it to work! 
in my case, after setting up xdebug, i found  i was having an other previous error with curl:
"SSL certificate problem: unable to get local issuer certificate"
i then followed the steps here to solve this problem: https://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate

**Comment by duykhoa87** [comment] 2021-07-29 08:45
I am facing this issue when update from 16 to master. Anyone can help it.
`[2021-07-29 07:59:43] develop.ERROR: Missing auth url {"exception":"[object] (Osiset\\ShopifyApp\\Exceptions\\MissingAuthUrlException(code: 0): Missing auth url at /usr/share/nginx/html/shopify-app/vendor/osiset/laravel-shopify/src/Traits/AuthController.php:47)
[stacktrace]`

**Comment by KevinSHansen** [comment] 2021-07-30 10:32
Did you manage to solve this?

**Comment by osiset** [comment] 2021-07-30 12:00
Search missing auth url on issues here, someone solved it previously. The config needs to be refreshed if upgrading from 16 to 17.

**Comment by KevinSHansen** [comment] 2021-07-30 12:23
@osiset ive already upgraded the shopify-app config and changed the attributes aswell.

But its still having issues.

**Comment by kaya-mikail** [comment] 2021-08-02 16:05
Anyone resolved this problem? Im facing the same issue.

**Comment by osiset** [comment] 2021-08-06 13:52
I can replicate, it hard for me to provide a solution atm.

**Comment by mudassirali007** [comment] 2021-08-25 12:02
facing the same issue at fresh install.

**Comment by julesgilson** [comment] 2021-11-22 09:24
As a number of people have pointed out - this is most likely caused by guzzle/curl not being able to validate the TLS certificate of your Shopify store. Unless you have a certificate authority bundle in place on the host then this will fail.

- Details on the curl website:
- [https://curl.se/docs/sslcerts.html](https://curl.se/docs/sslcerts.html)

There are many ways to tell curl where to find a CA bundle - perhaps the simplest is to use PHP:

[https://www.php.net/manual/en/curl.configuration.php](https://www.php.net/manual/en/curl.configuration.php)

- Just download the latest CA Bundle from curl:
- [https://curl.se/docs/caextract.htm](https://curl.se/docs/caextract.html)
- And point the `curl.cainfo` directive in php.ini at it. As the certs change over time, you will need to get a fresh copy of the bundle occasionally.

More robust methods are mentioned in the first link above.

**Comment by Kyon147** [comment] 2022-02-13 12:53
Closing as aged ticket.

**Closed by Kyon147** 2022-02-13 12:53 UTC

**Comment by Mbilalyounas** [comment] 2022-05-26 08:01
If you are using laravel for app development you just need to run just 
composer update 
php atrisan migrate
