### ISSUE TITLE
Change Plan

### ISSUE THREAD

**Issue by faisal-saeed-brainx** [osiset/laravel-shopify#420] opened 2020-03-18 12:12 UTC
Hi @osiset 

I have one question:

In plans table, I have two plans
1) Free Plan oninstall
2) Pro Plan monthly recurring

I am switching between plans (upgrading/downgrading) by this way.

```
public function activateProPlan()
{
    return redirect()->route('billing', 2);
}
```

This method goes on charge screen, to take user approval for charge. then it redirects back to home route. But when it reaches back to home route "shop domain not found" error happens.

Could you please guide me Is it the correct way to switch plan by calling billing route by passing the plan ID. Your help will be really appreciated

Regards
Faisal Saeed

**Comment by Kyon147** [comment] 2020-03-18 12:26
Are you using a pre v11 version of the package? This seems to be coming up a lot - the shop domain not found on charge.

**Comment by faisal-saeed-brainx** [comment] 2020-03-18 12:46
Hi @Kyon147 

I am using v10.3.1 currently. let me check by upgrading to pre v11, then I will let you know. Many thanks for your kind response.

**Comment by osiset** [comment] 2020-03-18 12:51
Hi @faisal-saeed-brainx 

Upgrading to v11 is not directly/easily possible. What you're doing seems correct, but I suspect the session cookie is lost somewhere.

I currently don't have the personal man-power to handle v10 issues at this time, but if the issues is present in v11, I'll certainly be able to look.

**Comment by Kyon147** [comment] 2020-03-18 13:25
@osiset @faisal-saeed-brainx 

As I still have an app on pre-v11 and won't switch it over straight away. I'll do some testing on this tonight and see if I can see what the issue is. I'll need to fix it for my own app anyway - so can post the results in here if any.

**Comment by osiset** [comment] 2020-03-18 16:02
I can create a branch off of the last v10 release and if such a fix is found, a PR can be sent to the branch and a patch release pushed for it.

**Comment by Kyon147** [comment] 2020-03-18 17:34
> I can create a branch off of the last v10 release and if such a fix is found, a PR can be sent to the branch and a patch release pushed for it.

Yeah no worries, I am looking into it now - just trying to make the error happen so I can see where the session is being lost.

**Comment by Kyon147** [comment] 2020-03-18 18:29
Think I have found the issue, on local at least. The issue is with the handlebadsession function mixed with an ngrok or any proxy.

According to the docs about [HTTP Requests](https://laravel.com/docs/5.8/requests#configuring-trusted-proxies)

> When running your applications behind a load balancer that terminates TLS / SSL certificates, you may notice your application sometimes does not generate HTTPS links

What happens:

1. Authenticate (AuthControllerTrait) tried to validate the shop
2. This then checks to see if we have a valid session (which we won't if you delete cookies or it just times out.
3. So it goes to handleBadSession() which then drops everything and starts again. 

This is where the issue comes in.

Currently, we are on https://xxxxx.ngrok.com but inside that function, we do this

`  Session::put('return_to', $request->fullUrl());`

Under the hood, as per the HTTP Requests doc, if it is not a trusted proxy it will only return HTTP.

So now our return_to is **http://**xxxxx.ngrok.com

Now the session has changed again from https to https, which then again checks again to see if we are validated. Does the full page redirect, then goes to check if we have a shop domain.

As we don't it goes down the list and then throws the missing domain exception.

I tested by adding `protected $proxies ='*';` in Middleware > TrustedProxies.php and it works correctly because the return_to gets set using https.

This works for both expired sessions and for billing.

The reason billing happens is that as part of being thrown over to accept the billing charge the current session is lost. So it needs to reauth again, without the correct return too you just get no session.

It's worth noting this never happens on my live server, for production or staging. Only when using ngrok do you seem to get this problem.

**Comment by osiset** [comment] 2020-03-18 19:13
Hmm great investigation. Yeah ngork has caused many issues with people trying to develop a package in development, with webhooks and more.On Mar. 18, 2020 16:00, Luke Walsh <notifications@github.com> wrote:
Think I have found the issue, on local at least. The issue is with the handlebadsession function mixed with an ngrok or any proxy.
According to the docs about HTTP Requests

When running your applications behind a load balancer that terminates TLS / SSL certificates, you may notice your application sometimes does not generate HTTPS links

What happens:
Authenticate (AuthControllerTrait) tried to validate the shopThis then checks to see if we have a valid session (which we won't if you delete cookies or it just times out.So it goes to handleBadSession() which then drops everything and starts again.
This is where the issue comes in.
Currently, we are on https://xxxxx.ngrok.com but inside that function, we do this
  Session::put('return_to', $request->fullUrl());
Under the hood, as per the HTTP Requests doc, if it is not a trusted proxy it will only return HTTP.
So now our return_to is **http://**xxxxx.ngrok.com
Now the session has changed again from https to https, which then again checks again to see if we are validated. Does the full page redirect, then goes to check if we have a shop domain.
As we don't it goes down the list and then throws the missing domain exception.
I tested by adding protected $proxies ='*'; in Middleware > TrustedProxies.php and it works correctly because the return_to gets set using https.
This works for both expired sessions and for billing.
The reason billing happens is that as part of being thrown over to accept the billing charge the current session is lost. So it needs to reauth again, without the correct return too you just get no session.
It's worth noting this never happens on my live server, for production or staging. Only when using ngrok do you seem to get this problem.

**Comment by Kyon147** [comment] 2020-03-18 19:31
Yeah it took me a little while to figure out what was happening as I couldn't replicate it at first.

To be honest the way Laravel works it wouldn't be a bad shout to add your local host in the trusted proxy even on a server. At least you know internal requests will still be passed with SSL that way and not forced to HTTP.

**Comment by faisal-saeed-brainx** [comment] 2020-03-19 10:11
@Kyon147 

I really appreciate your work. I have added `protected $proxies ='*';` and then switch plan. Now it is working fine. I will do more testing to ensure that all of the other auth routes are working fine by doing this hack.

**Comment by Kyon147** [comment] 2020-03-19 10:13
> @Kyon147
> 
> I really appreciate your work. I have added `protected $proxies ='*';` and then switch plan. Now it is working fine. I will do more testing to ensure that all of the other auth routes are working fine by doing this hack.

On local using `*` is fine, if you are on production, you might want to just set it to `protected $proxies ='127.0.0.1';`

This just reduces the chance of any unauthorised access, as a "allow all" is not very good practice for anything really.

Glad it helped though 👍

**Comment by Kyon147** [comment] 2020-03-19 10:18
Closing the issue for now as this seems like an okay fix for pre-v11.

**Closed by Kyon147** 2020-03-19 10:18 UTC
Labels: pre-v11
