### ISSUE TITLE
V17 Billing Route Not Wokring 

### ISSUE THREAD

**Issue by hamzasgd** [osiset/laravel-shopify#872] opened 2021-07-08 07:47 UTC
InvalidArgumentException
Can only instantiate this object with a string.

**Comment by andreuka** [comment] 2021-07-08 11:39
No route works in safari, only homepage:

"Can only instantiate this object with a string."

**Comment by BrandonR-16** [comment] 2021-07-08 11:40
Dealing with the same thing. Not with billing, but with authenticate. Giving the exact same error.

**Comment by Enmaboya** [comment] 2021-07-08 11:42
give examples of code.
also write the browser you are using, the operating system, etc.

without this it is impossible to reproduce your problem

**Comment by andreuka** [comment] 2021-07-08 11:44
@Enmaboya do you using package with turbolinks?

**Comment by hamzasgd** [comment] 2021-07-08 11:47
Found the problem missing shop parameter in the URL

**Comment by andreuka** [comment] 2021-07-08 11:49
> Found the problem missing shop parameter in the URL

do you have fix?

**Comment by hamzasgd** [comment] 2021-07-08 11:49
Yes, I think this is not mention in upgrade guide but available in billing section of the wiki

**Comment by hamzasgd** [comment] 2021-07-08 11:50
This is the new 
{{ route('billing', ['plan' => 2, 'shop' => Auth::user()->name]) }}

**Comment by hamzasgd** [comment] 2021-07-08 11:50
In v16 only plan param is needed

**Comment by andreuka** [comment] 2021-07-08 11:51
> This is the new
> {{ route('billing', ['plan' => 2, 'shop' => Auth::user()->name]) }}

Duh, all my routes are broken when using without turbolinks.
Are you with turbolinks?

**Comment by Enmaboya** [comment] 2021-07-08 12:14
> @Enmaboya do you using package with turbolinks?

depends on the application.
some with turbolinks, some without.

all work the same.

and yes, for safari and private mode (e.g. in chrome), you need to pass the second parameter
" 'shop' => Auth::user()->name"

**Comment by andreuka** [comment] 2021-07-08 12:16
> > @Enmaboya do you using package with turbolinks?
> 
> depends on the application.
> some with turbolinks, some without.
> 
> all work the same.
> 
> and yes, for safari and private mode (e.g. in chrome), you need to pass the second parameter
> " 'shop' => Auth::user()->name"

But do you have multipages applications (server rendered) without turbolinks, right?
So all issue is we need to add shop to all links?

**Comment by BrandonR-16** [comment] 2021-07-08 12:16
> > @Enmaboya do you using package with turbolinks?
> 
> depends on the application.
> some with turbolinks, some without.
> 
> all work the same.
> 
> and yes, for safari and private mode (e.g. in chrome), you need to pass the second parameter
> " 'shop' => Auth::user()->name"

Where do you pass this parameter. Sort of new to Laravel so I'm kinda confused

**Comment by andreuka** [comment] 2021-07-08 12:17
> > > @Enmaboya do you using package with turbolinks?
> > 
> > 
> > depends on the application.
> > some with turbolinks, some without.
> > all work the same.
> > and yes, for safari and private mode (e.g. in chrome), you need to pass the second parameter
> > " 'shop' => Auth::user()->name"
> 
> Where do you pass this parameter. Sort of new to Laravel so I'm kinda confused

seems like it needs to be added for all links.

**Comment by Enmaboya** [comment] 2021-07-08 12:21
> seems like it needs to be added for all links.

No, for all other links (except for post requests) you should have in your layout template
@include('shopify-app::partials.token_handler')

**Comment by BrandonR-16** [comment] 2021-07-08 12:27
> > seems like it needs to be added for all links.
> 
> No, for all other links you should have in your layout template
> @include('shopify-app::partials.token_handler')
> 
> and add @sessionToken for post requests

Could you provide an example of where @include('shopify-app::partials.token_handler') goes in your code and how it's used?

**Comment by andreuka** [comment] 2021-07-08 12:28
> > > seems like it needs to be added for all links.
> > 
> > 
> > No, for all other links you should have in your layout template
> > @include('shopify-app::partials.token_handler')
> > and add @sessionToken for post requests
> 
> Could you provide an example of where @include('shopify-app::partials.token_handler') goes in your code and how it's used?

its included by default in latest version of package, but it doesnt solve anything when using without turbolinks for me

**Comment by BrandonR-16** [comment] 2021-07-08 12:29
> > > > seems like it needs to be added for all links.
> > > 
> > > 
> > > No, for all other links you should have in your layout template
> > > @include('shopify-app::partials.token_handler')
> > > and add @sessionToken for post requests
> > 
> > 
> > Could you provide an example of where @include('shopify-app::partials.token_handler') goes in your code and how it's used?
> 
> its included by default in latest version of package, but it doesnt solve anything when using without turbolinks for me

Yeah I'm in the boat

**Comment by andreuka** [comment] 2021-07-08 12:31
> > > > > seems like it needs to be added for all links.
> > > > 
> > > > 
> > > > No, for all other links you should have in your layout template
> > > > @include('shopify-app::partials.token_handler')
> > > > and add @sessionToken for post requests
> > > 
> > > 
> > > Could you provide an example of where @include('shopify-app::partials.token_handler') goes in your code and how it's used?
> > 
> > 
> > its included by default in latest version of package, but it doesnt solve anything when using without turbolinks for me
> 
> Yeah I'm in the same boat

Add ?shop=current-shop.myshopify.com to all your links, this seems to be solving issue

**Comment by Enmaboya** [comment] 2021-07-08 12:32
[here](https://github.com/osiset/laravel-shopify/blob/master/src/ShopifyApp/resources/views/layouts/default.blade.php)

But, it is not necessary for billing.
_________
Simply add the "shop" parameter to the route for billing

**Comment by andreuka** [comment] 2021-07-08 12:33
> [here](https://github.com/osiset/laravel-shopify/blob/master/src/ShopifyApp/resources/views/layouts/default.blade.php)
> 
> But, it is not necessary for billing.
> 
> Simply add the "shop" parameter to the route for billing

not work out of the box for some reason :(

**Comment by andreuka** [comment] 2021-07-08 12:42
> > > > > seems like it needs to be added for all links.
> > > > 
> > > > 
> > > > No, for all other links you should have in your layout template
> > > > @include('shopify-app::partials.token_handler')
> > > > and add @sessionToken for post requests
> > > 
> > > 
> > > Could you provide an example of where @include('shopify-app::partials.token_handler') goes in your code and how it's used?
> > 
> > 
> > its included by default in latest version of package, but it doesnt solve anything when using without turbolinks for me
> 
> Yeah I'm in the same boat

Fix with JS:

`
var shopOrigin = '{{ Auth::user()->name }}';

$(document).ready(function () {
$('a[href]').each(function(){
        if(location.hostname === this.hostname || !this.hostname.length) {
            var a = $(this);
            var href = a.attr('href');
            var url = addToQueryString(href, 'shop', shopOrigin);

            a.attr('href', url);
        }
    });
    function addToQueryString(url, key, value) {
        var query = url.indexOf('?');
        var anchor = url.indexOf('#');
        if (query == url.length - 1) {
            // Strip any ? on the end of the URL
            url = url.substring(0, query);
            query = -1;
        }
        return (anchor > 0 ? url.substring(0, anchor) : url)
            + (query > 0 ? "&" + key + "=" + value : "?" + key + "=" + value)
            + (anchor > 0 ? url.substring(anchor) : "");
    }
    });`

**Comment by BrandonR-16** [comment] 2021-07-08 12:50
That worked! Thank you so much! :)

**Comment by osiset** [comment] 2021-07-09 15:30
@hamzasgd 

`{{ URL::tokenRoute('billing', ['plan' => 2, 'shop' => Auth::user()->name]) }}`

Should work.. I should maybe auto-add `shop` param to append with `tokenRoute`...

**Comment by hamzasgd** [comment] 2021-07-09 15:39
> @hamzasgd
> 
> `{{ URL::tokenRoute('billing', ['plan' => 2, 'shop' => Auth::user()->name]) }}`
> 
> Should work.. I should maybe auto-add `shop` param to append with `tokenRoute`...

@osiset Yes that's a good idea.

**Comment by Kyon147** [comment] 2021-11-03 15:19
'shop' was added automatically to `Url:tokenRoute()`on release #847 so closing this now.

**Closed by Kyon147** 2021-11-03 15:19 UTC
