### ISSUE TITLE
Not embedded Shopify app

### ISSUE THREAD

**Issue by abdelmoughit555** [osiset/laravel-shopify#862] opened 2021-07-04 12:55 UTC
Hello everyone!
## Expected Behavior

I'm planning on building a non embedded Shopify but when I disabled it from Shopify app and setting `SHOPIFY_APPBRIDGE_ENABLED = false` when I try to install the app in my store, the page gets stuck in loading screen.
The shop is registered in in my database.

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v17
* Laravel Version: v8
* Using a toolset Vagrant

Please include any relevant log snippets or files here.
<img width="932" alt="Screen Shot 2021-07-04 at 13 54 43" src="https://user-images.githubusercontent.com/26329383/124385843-6ffb1900-dccf-11eb-9c4b-0f9af1d604a1.png">

Thanks everyone!

**Comment by abdelmoughit555** [comment] 2021-07-04 13:16
What I noticed is that version 17 does not support `auth.shopify` anymore. Should I use version 16 if I wanted to use not embedded Shopify app?

**Comment by Enmaboya** [comment] 2021-07-04 19:01
version 16 uses cookies, so I wouldn't recommend using it

**Comment by abdelmoughit555** [comment] 2021-07-04 19:46
> version 16 uses cookies, so I wouldn't recommend using it
Thank you ! but is there a way to you version 17 without embedding my app?

**Comment by Enmaboya** [comment] 2021-07-04 20:08
> Thank you ! but is there a way to you version 17 without embedding my app? my app design is different that Shopify's, thats why I'm trying to not use embedded option

specifically with version 17 I didn't do this.
but I'll try it tomorrow and report back, I'm curious about it myself.

**Comment by khiconit** [comment] 2021-07-05 08:09
Same issue

**Comment by abdelmoughit555** [comment] 2021-07-05 08:17
> > Thank you ! but is there a way to you version 17 without embedding my app? my app design is different that Shopify's, thats why I'm trying to not use embedded option
> 
> specifically with version 17 I didn't do this.
> but I'll try it tomorrow and report back, I'm curious about it myself.


Thank you!

**Comment by hamzasgd** [comment] 2021-07-05 10:51
How to solve this?

**Comment by khiconit** [comment] 2021-07-05 10:53
I downgraded to ver 16 to work with non-embed app.

**Comment by hamzasgd** [comment] 2021-07-05 11:04
So ver 17 will not work for embedded apps?

**Comment by khiconit** [comment] 2021-07-05 11:20
I thinl that v17 only work with emmbed app

**Comment by hamzasgd** [comment] 2021-07-05 11:32
> I think that v17 only work with emmbed app

Yes I am using it with embedded but the problem is same.

**Comment by abdelmoughit555** [comment] 2021-07-05 14:38
> I downgraded to ver 16 to work with non-embed app.


Can you use version 16 without Shopify rejects your app?

**Comment by osiset** [comment] 2021-07-05 20:27
@abdelmoughit555 I believe with tokens we will be tied to AppBridge and embedded at this point. I think I will have to deprecate the setting.

**Comment by abdelmoughit555** [comment] 2021-07-05 20:31
> @abdelmoughit555 I believe with tokens we will be tied to AppBridge and embedded at this point. I think I will have to deprecate the setting.


Thank you for your comment! I just wanna ask if its ok to use version 16 if i dont want my app to be embedded?

**Comment by Enmaboya** [comment] 2021-07-06 07:32
> Thank you for your comment! I just wanna ask if its ok to use version 16 if i dont want my app to be embedded?

your app will most likely not pass the moderation of the shopifoy.

and, at the very least, will not work in safari.


I've tried deploying a non-embedded app, it can be achieved quite well, but most likely you will have to use some third party solution to get the jwt tokens. and, preferably make a spa app in such a case

**Comment by abdelmoughit555** [comment] 2021-07-06 15:10
> > Thank you for your comment! I just wanna ask if its ok to use version 16 if i dont want my app to be embedded?
> 
> your app will most likely not pass the moderation.
> 
> and, at the very least, will not work in safari.
> 
> I've tried deploying a non-embedded app, it can be achieved quite well, but most likely you will have to use some third party solution to get the jwt tokens. and, preferably make a spa app in such a case


I'm planning on using your suggestion, I'm trying to build a spa app non-embedded using jwt token. If my app will get rejected i will switch easily to version 17 (hopefully). Thanks for your suggestion!

**Comment by osiset** [comment] 2021-07-08 19:44
Thanks, I'll close this for now, I'll update the wiki this week to note only embedded is currently supported.
If you get info on getting the tokens outside of Shopify, that'd be interesting.

**Closed by osiset** 2021-07-08 19:44 UTC
