### ISSUE TITLE
Call to a member function getId() on null

### ISSUE THREAD

**Issue by DanielChritisan** [osiset/laravel-shopify#1044] opened 2021-12-28 18:48 UTC
I am creating the billing app with usage-based charge and I have followed this https://github.com/osiset/laravel-shopify/wiki/Creating-a-Billable-App

## Expected Behavior
Successfully create the usage-based charges.

## Current Behavior

Currently, it's giving Call to a member function getId() on null error

## Failure Information
![image](https://user-images.githubusercontent.com/35802146/147596845-7d533916-cbce-4ed8-9ca4-6276a0601a88.png)
![image](https://user-images.githubusercontent.com/35802146/147596864-34f99ebd-dc5e-46a0-a45e-8b4c0a4f788b.png)

### Steps to Reproduce
1. Create Usage-Based charges: 
![image](https://user-images.githubusercontent.com/35802146/147597111-c1ab4593-cf65-4fcd-8800-51671250a1bf.png)
2. Redirect to usage-based charges URL:
![image](https://user-images.githubusercontent.com/35802146/147597138-d21399a4-a2dd-4afb-9895-04a664c316a7.png)

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v17.1.0
* Laravel Version: v8.55.0
* PHP Version: 7.4.26
* Using a toolset (Docker, Laradock, Vagrant, etc.): ngrok

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Kyon147** [comment] 2022-09-13 14:57
Duplicate of #1002

**Closed by Kyon147** 2022-09-13 14:57 UTC
