### ISSUE TITLE
You cannot request a merchant's .myshopify.com URL

### ISSUE THREAD

**Issue by abimwaqas** [osiset/laravel-shopify#1119] opened 2022-04-14 09:49 UTC
I am trying to get my app listed on the Shopify store. While fulfilling there numerous requirements. This is one which I am now totally stuck on.

Their last response mentions: "You cannot request a merchant's .myshopify.com URL", can anyone guide me what should I do? The screenshot they shared for reference is the  following.

![Shopify Listing Issue](https://user-images.githubusercontent.com/36468495/163360406-52a443ba-f985-44df-b27d-927ca047eaab.png)

**Comment by Kyon147** [comment] 2022-04-15 12:42
Hi @abimwaqas 

Can you screenshot their actual response from the review? That's not a lot of information to go off.

This sort of request does sit outside the "issues" as it is not a bug/issue related to the package that I can see but more the app set up.

**Comment by abimwaqas** [comment] 2022-04-15 13:00
It's actually more like this issue https://github.com/osiset/laravel-shopify/issues/1073 the installation process is different for
![Screenshot 2022-04-15 175013](https://user-images.githubusercontent.com/36468495/163572789-3fd83b1d-ee43-4d6f-90d8-85d3e1533802.png)
and the links are as follows
Requirements: https://shopify.dev/apps/store/requirements#a-authentication
I resolved the second issue mentioned in the point which occurs in case uninstalled webhook was not triggering and now i'm just deleting the shop on uninstall instead of soft delete. But main issue is access token needs to get after the grant_request not before.

**Comment by clydesantiago** [comment] 2022-05-22 08:01
I resolved the issue by redirecting the `/login` to Shopify App Store (apps.shopify.com) this should be redirected to your specific app listing later on once published.

As per Shopify, you should not accept `.myshopify.com` in the field usually being used in login page.

**Comment by Kyon147** [comment] 2022-09-11 06:57
Closing out this ticket as it seems to be resolved but please re-open if the issue persists.

**Closed by Kyon147** 2022-09-11 06:57 UTC
Labels: question
