### ISSUE TITLE
Call to a member function getDomain() on null in Safari

### ISSUE THREAD

**Issue by artem55555p** [osiset/laravel-shopify#1067] opened 2022-01-25 06:58 UTC
I logged in https://partners.shopify.com/xxxxxxx/resources/get_started to the Apps section. ->Test Application -> Select Store -> name-store. The error is only in safari. Chrome and Mozilla are fine.
Does anyone have any ideas?

![изображение](https://user-images.githubusercontent.com/12828397/150926505-5223dbd9-98ef-44e0-a105-f7172e44fec4.png)

**Comment by Sanjay-100** [comment] 2022-01-25 10:37
@artem55555p   This is not package  Error you have to check the database you clean-up manfully  so Delete app and Install again.

**Comment by Kyon147** [comment] 2022-03-22 11:48
I've tested this successfully on my own apps and new blank build. Closing it for now as the issue is quite old. Reopen if it still exists.

**Closed by Kyon147** 2022-03-22 11:48 UTC
