### ISSUE TITLE
Laravel 8 install problem

### ISSUE THREAD

**Issue by theduman** [osiset/laravel-shopify#571] opened 2020-09-09 19:05 UTC
## Expected Behavior

Installing package via composer require osiset/laravel-shopify

## Current Behavior

Getting error on install

## Failure Information

After fresh laravel 8 installation, tried to install shopify package via composer but i got this error. After error I installed on laravel 7.28 version and installed correctly.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for osiset/laravel-shopify ^12.1 -> satisfiable by osiset/laravel-shopify[v12.1.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].

### Steps to Reproduce

1. Install laravel 8
2. Install package with composer

### Context

* Package Version: v12.1
* Laravel Version: v8.0.0
* PHP Version: v7.4.9

**Comment by osiset** [comment] 2020-09-11 15:28
Just merged in a couple PRs to assist with this from the community.

Locally the unit tests are passing with Laravel 8.1 but I have yet to try a real install yet as it was just released.

You're welcome to pull master and give it a try, but no release has been made yet until I can test this out on a real install.

**Comment by lucasmichot** [comment] 2020-09-12 14:04
Hey @osiset, I could also reproduce the issue.
I guess that a new release for this package needs to be created

**Comment by awebartisan** [comment] 2020-09-12 18:20
Underlying package [Basic-Shopify-API](https://packagist.org/packages/osiset/basic-shopify-api) requires `guzzlehttp/guzzle: ^6.5` but Laravel 8 project requires `"guzzlehttp/guzzle": "^7.0.1"`. Therefore, unable to install.

@osiset open an issue for this on Basic-Shopify-API repo since it also kinda belong there.

**Comment by osiset** [comment] 2020-09-14 13:34
The underlying package has been updated. This repo has a PR by me to bump it to the new version.

Theres one PR pending by a contributor which needs a minor adjustment.

Once that is solved, unit tests appear to be fine, I will be installing on a Laravel 8 installation and if all is well, i'll push a new release.

**Comment by osiset** [comment] 2020-09-15 15:34
Tested on Laravel 8.3. Did not run into issues. Will be pushing a release.

**Comment by osiset** [comment] 2020-09-15 16:05
Release drafted, change log drafted, upgrade doc drafted. Just checking a few other things - but a release tonight should be possible unless I overlooked something (which I'm confirming now).

**Comment by acanza** [comment] 2020-09-17 08:36
Hi @osiset !

When do you think the next release will be available?

**Comment by osiset** [comment] 2020-09-17 13:05
Just released. This is a major bump so be aware of the big changes in changelog, namely the first 3 items.

```conf
- Add Laravel 8 support (#570)
- API library updated to support Laravel 8 / Guzzle 7 (#582)
- Removal of "login" route and view
- Unused script tags auto-deleted (#543)
- Unused webhooks auto-deleted
```

**Comment by lucasmichot** [comment] 2020-09-17 13:06
Congrats @osiset 👏

**Closed** 2020-09-17 13:06 UTC
Labels: feature

**Comment by awebartisan** [comment] 2020-09-17 14:13
Thank you @osiset 🎉❤️

**Comment by acanza** [comment] 2020-09-17 15:24
You are the best @osiset 👏🏻
